[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.30"

remappings = [
  "@openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"
